//
//  WithoutResultUserListWireframe.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 26/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

struct WithoutResultUserListContext {
}

final class WithoutResultUserListWireframe: NSObject {
    
    // MARK: - Private properties -

    private var _context: WithoutResultUserListContext?
    private let _storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
    
    // MARK: - Public properties -
    
    weak var navigationController: UINavigationController?
    weak var viewController: UIViewController?
    
    // MARK: - Init -
    
    private override init() {}

    init(context: WithoutResultUserListContext? = nil, navigationController: UINavigationController? = nil) {
        super.init()
        _context = context
        self.navigationController = navigationController
    }
    
    // MARK: - Module setup -
    
    func instantiateAndConfigureModule() -> UIViewController {
        let moduleViewController = _storyboard.instantiateViewControllerWithIdentifier("UserListViewController") as! UserListViewController
        configureModuleWith(moduleViewController)
        viewController = moduleViewController
        return moduleViewController
    }
    
    func configureModuleWith(viewController: UserListViewController) {
        let interactor = WithoutResultUserListInteractor()
        let presenter = WithoutResultUserListPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }

}

// MARK: - UserList Wireframe Interface Requirements -

extension WithoutResultUserListWireframe: UserListWireframeInterface {
    
    func performNavigationAction(action: UserListNavigationAction) {
        switch action {
        // #warning Implement actions
        default:
            break
        }
    }

    func configureChildViewController(viewController: UIViewController) {
        // #warning Incomplete implementation, remove if not needed
        /*
        let wireframe = <#ChildWireframe#>(navigationController: navigationController)
        wireframe.configureModuleWith(viewController)
        */
    }

}