//
//  MainViewController.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 26/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

private enum RowIdentifier: Int {
    case WithoutResult
    case WithResult
}

import UIKit

// MARK: -  Main View Controller -
final class MainViewController: UITableViewController {
    
    // MARK: - Public properties -
    
    var presenter: MainViewDelegateInterface!
    
    // MARK: - View lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        _configureUI()
    }
  
    // MARK: - Public functions -

    // MARK: - IBActions -
  
    // MARK: - Private functions -
    
    private func _configureUI() {
        // Title
        title = "Examples"
    }
    
    // MARK: - UITableViewDelegate -
    
    override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        guard let rowIdentifier = RowIdentifier(rawValue: indexPath.row) else {
            return
        }
        
        switch rowIdentifier {
        case .WithoutResult:
            presenter.didSelectNavigationAction(.WithoutResultExample)
        case .WithResult:
            presenter.didSelectNavigationAction(.WithResultExample)
        }
    }
}

// MARK: - Extensions -

extension MainViewController: MainViewInterface {
}
