//
//  MainWireframe.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 26/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

struct MainContext {
}

final class MainWireframe: NSObject {
    
    // MARK: - Private properties -

    private var _context: MainContext?
    private let _storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
    
    // MARK: - Public properties -
    
    weak var navigationController: UINavigationController?
    weak var viewController: UIViewController?
    
    // MARK: - Init -
    
    private override init() {}

    init(context: MainContext? = nil, navigationController: UINavigationController? = nil) {
        super.init()
        _context = context
        self.navigationController = navigationController
    }
    
    // MARK: - Module setup -
    
    func instantiateAndConfigureModule() -> UIViewController {
        let moduleViewController = _storyboard.instantiateViewControllerWithIdentifier("MainViewController") as! MainViewController
        configureModuleWith(moduleViewController)
        viewController = moduleViewController
        return moduleViewController
    }
    
    func configureModuleWith(viewController: MainViewController) {
        let presenter = MainPresenter(wireframe: self, view: viewController)
        viewController.presenter = presenter
    }

}

// MARK: - Main Wireframe Interface Requirements -

extension MainWireframe: MainWireframeInterface {
    
    func performNavigationAction(action: MainNavigationAction) {
        switch action {
        case .WithoutResultExample:
            let wireframe = WithoutResultUserListWireframe()
            let viewController = wireframe.instantiateAndConfigureModule()
            navigationController?.pushViewController(viewController, animated: true)
        case .WithResultExample:
            let wireframe = WithResultUserListWireframe()
            let viewController = wireframe.instantiateAndConfigureModule()
            navigationController?.pushViewController(viewController, animated: true)
        case .CommentsExample:
            let wireframe = CommentListWireframe()
            let viewController = wireframe.instantiateAndConfigureModule()
            navigationController?.pushViewController(viewController, animated: true)
        }
    }

}