//
//  MainInteractor.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 26/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MainInteractor: NSObject, MainInteractorInterface {
    
    // MARK: - Public functions -
    
    // MARK: - Private functions -
    
}
