//
//  MainInterfaces.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 26/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

// MARK: - Navigation -

enum  MainNavigationAction {
    case WithoutResultExample
    case WithResultExample
}

// MARK: - Main Wireframe Interface -

protocol MainWireframeInterface: WireframeInterface {
    func performNavigationAction(action: MainNavigationAction)
    func configureModuleWith(viewController: MainViewController)
}

// MARK: - Main View Interface -

protocol MainViewInterface: ViewInterface {
}

// MARK: - Main View Presenter (Delegate) Interface -

protocol MainViewDelegateInterface: PresenterInterface {
    func didSelectNavigationAction(action: MainNavigationAction)
}
