//
//  UserListInterfaces.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 26/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit
import Result

// MARK: - Navigation -

enum  UserListNavigationAction {
}

// MARK: - UserList Wireframe Interface -

protocol UserListWireframeInterface: WireframeInterface {
    func performNavigationAction(action: UserListNavigationAction)
    func configureModuleWith(viewController: UserListViewController)
}

// MARK: - UserList View Interface -

protocol UserListViewInterface: ViewInterface, Progressable {
    func reloadData()
}

// MARK: - UserList View Presenter (Delegate) Interface -

protocol UserListViewDelegateInterface: PresenterInterface {
    func didSelectNavigationAction(action: UserListNavigationAction)
    func numberOfItems() -> Int
    func itemAtIndexPath(indexPath: NSIndexPath) -> UserCellItem
}

// MARK: - UserList Interactor Interface -

protocol UserListInteractorInterface: InteractorInterface {
    // This is ignored for this example, but shouldn't be!
}
