//
//  UserListViewController.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 26/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: -  UserList View Controller -
final class UserListViewController: UIViewController {
    
    // MARK: - IBOutlets -
    
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: - Public properties -
    
    var presenter: UserListViewDelegateInterface!
    
    // MARK: - View lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        _configureUI()
        presenter.viewDidLoad()
    }
  
    // MARK: - Private functions -
    
    private func _configureUI() {
        title = "Users"
    }
}

// MARK: - Extensions -

extension UserListViewController: UserListViewInterface {
    
    func reloadData() {
        tableView.reloadData()
    }
    
}

extension UserListViewController: UITableViewDataSource, UITableViewDelegate {
    
    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.numberOfItems()
    }
    
    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier("Cell", forIndexPath: indexPath)
        let item = presenter.itemAtIndexPath(indexPath)
        
        cell.textLabel?.attributedText = item.nameAndWorkplace
        cell.detailTextLabel?.text = item.fullAddress
        
        return cell
    }
    
}
