//
//  CommentListInteractor.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 27/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Alamofire
import Unbox
import Result
import enum Result.Result

final class CommentListInteractor: NSObject, CommentListInteractorInterface {
    
    // MARK: - Public functions -
    
    func loadUsers(withResultHandler resultHandler: (Result<[Comment], NetworkError>) -> ()) {
        Alamofire
            .request(Router.Comments.URLRequest)
            .debugLog()
            .validate()
            .responseJSON { response in
                response.debugLog()
                
                resultHandler(response.result
                    .mapError { NetworkError.Alamofire($0) }
                    .map { $0 as? [UnboxableDictionary] ?? [] }            
                    .tryMap { try Unbox($0) as [Comment] })
        }
    }
    
}
