//
//  CommentListWireframe.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 27/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

struct CommentListContext {
}

final class CommentListWireframe: NSObject {
    
    // MARK: - Private properties -

    private var _context: CommentListContext?
    private let _storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
    
    // MARK: - Public properties -
    
    weak var navigationController: UINavigationController?
    weak var viewController: UIViewController?
    
    // MARK: - Init -
    
    private override init() {}

    init(context: CommentListContext? = nil, navigationController: UINavigationController? = nil) {
        super.init()
        _context = context
        self.navigationController = navigationController
    }
    
    // MARK: - Module setup -
    
    func instantiateAndConfigureModule() -> UIViewController {
        let moduleViewController = _storyboard.instantiateViewControllerWithIdentifier("CommentListViewController") as! CommentListViewController
        configureModuleWith(moduleViewController)
        viewController = moduleViewController
        return moduleViewController
    }
    
    func configureModuleWith(viewController: CommentListViewController) {
        let interactor = CommentListInteractor()
        let presenter = CommentListPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }

}

// MARK: - CommentList Wireframe Interface Requirements -

extension CommentListWireframe: CommentListWireframeInterface {
    
    func performNavigationAction(action: CommentListNavigationAction) {
        switch action {
        // #warning Implement actions
        default:
            break
        }
    }
    
}