//
//  CommentListViewController.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 27/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CommentListViewController: UIViewController {
    
    // MARK: - IBOutlets -
    
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: - Public properties -
    
    var presenter: CommentListViewDelegateInterface!
    
    // MARK: - View lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        _configureUI()
        presenter.viewDidLoad()
    }
    
    // MARK: - Private functions -
    
    private func _configureUI() {
        title = "Comments"
    }
}

// MARK: - Extensions -

extension CommentListViewController: CommentListViewInterface {
    
    func reloadData() {
        tableView.reloadData()
    }
    
}

extension CommentListViewController: UITableViewDataSource, UITableViewDelegate {
    
    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.numberOfItems()
    }
    
    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier("Cell", forIndexPath: indexPath)
        let item = presenter.itemAtIndexPath(indexPath)
        
        cell.textLabel?.attributedText = item.name
        cell.detailTextLabel?.text = item.body
        
        return cell
    }
    
}
