//
//  WithResultUserListPresenter.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 26/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire
import Unbox
import Result
import enum Result.Result

final class WithResultUserListPresenter: NSObject {
    
    // MARK: - Private properties -

    private weak var _view: UserListViewInterface?
    private var _interactor: WithResultUserListInteractor
    private var _wireframe: UserListWireframeInterface
    
    private var _items = [UserCellItem]()
    
    // MARK: - Lifecycle -
    
    init (wireframe: UserListWireframeInterface, view: UserListViewInterface, interactor: WithResultUserListInteractor) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

    // MARK: - Private functions -
    
}

// MARK: - Extensions -

extension WithResultUserListPresenter: UserListViewDelegateInterface {
    
    func viewDidLoad() {
        _view?.showLoading()
        _interactor.loadUsers { [weak self] result in
            let transformedResult = result.map { $0.map { UserCellItem(user: $0) } }
            
            switch transformedResult {
            case .Success(let userCellItems):
                self?._items.appendContentsOf(userCellItems)
                self?._view?.reloadData()
                self?._view?.hideLoading()
            case .Failure(let networkError):
                self?._view?.hideWithError(message: networkError.message)
            }
        }
    }
    
    func didSelectNavigationAction(action: UserListNavigationAction) {
        _wireframe.performNavigationAction(action)
    }
    
    func numberOfItems() -> Int {
        return _items.count
    }
    
    func itemAtIndexPath(indexPath: NSIndexPath) -> UserCellItem {
        return _items[indexPath.row]
    }
    
}
