//
//  WithResultUserListInteractor.swift
//  ResultExample
//
//  Created by Vedran Burojevic on 26/09/2016.
//  Copyright (c) 2016 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Alamofire
import Unbox
import Result
import enum Result.Result

final class WithResultUserListInteractor: NSObject, UserListInteractorInterface {
    
    // MARK: - Public functions -
    
    func loadUsers(withResultHandler resultHandler: (Result<[User], NetworkError>) -> ()) {
        Alamofire
            .request(Router.Users.URLRequest)
            .debugLog()
            .validate()
            .responseJSON { response in
                response.debugLog()
                
                resultHandler(response.result // Result<AnyObject, NSError>
                    .mapError { NetworkError.Alamofire($0) } // Result<AnyObject, NetworkError>
                    .map { $0 as? [UnboxableDictionary] ?? [] } // Result<[UnboxableDictionary], NetworkError>         
                    .tryMap { try Unbox($0) as [User] }) // Result<[User], NetworkError> 
        }
    }
    
}
